### ISSUE TITLE
Crash when 6 troops exist in islamist rule country and choosing regime change option (which should not have been there)

### ISSUE THREAD

**Issue by justinkwaugh** [sellmerfud/awakening#2] opened 2018-05-04 20:50 UTC
It's a weird situation but definitely can happen.  I did a regime change in afghanistan, and subsequently the jihadists managed to get all their cells in there and pull off a major jihad.  At that point you cannot do a regime change with the existing troops, and in my case I did not have enough in the tracks to deploy 6.  I was still offered the option of regime change when playing a 3 op card, and upon choosing it, the app crashed with an exception.

**Comment by sellmerfud** [comment] 2018-08-03 15:48
Good catch.  A corner case that I had not taken into account.
Fixed in release 2.11.

**Closed by sellmerfud** 2018-08-03 15:48 UTC

**Comment by akyazi16** [comment] 2019-03-05 21:27
I ran into this same issue yesterday.  Same circumstances.  There may still me an issue there.

**Comment by sellmerfud** [comment] 2019-03-05 21:45
> I ran into this same issue yesterday. Same circumstances. There may still me an issue there.

Which version are you using?

**Comment by akyazi16** [comment] 2019-03-05 21:47
I will double check to be sure when I get home, but I was almost positive it was 2.2. By the way, I never would’ve been able to play this game without your application. It’s amazing. Thanks for taking the time to put it together.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by sellmerfud** [comment] 2019-03-05 22:04
Thanks.  I'm glad you are enjoying it.
Did you mean 2.2  or 2.20 (which is the latest)?
When you get home, could you zip up the directory with your saved game files and attach it here.
Along with knowing your version number, I should be able to reproduce the problem which will make it much easier to find and fix.
Thanks.

**Comment by akyazi16** [comment] 2019-03-06 03:52
I have confirmed it is version 2.20

Requested files are attached.

Thanks!

Ben

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sellmerfud** [comment] 2019-03-06 04:30
The attachment didn't come through.   Try replying to me directly with the
attachment.  My email is sellmerfud @ gmail . com

I think I have found (and fixed) the problem.  When I get your game files I
will verify.

**Comment by sellmerfud** [comment] 2019-03-06 15:26
OK, problem fixed and verified.  Version 2.21 released.

**Comment by akyazi16** [comment] 2019-03-06 17:25
Thank you so much!

A suggestion and a question if you have the time…

I love the app as is!  Just a suggestion, though I imagine it isn’t the simplest thing to code (I don’t know the first thing about it), but have you ever given any thought to being able to input the number of times a player wants to go through the deck (game length), so you can give the app the ability to keep count of total cards played and recognize a “reshuffle” game-ending condition and, more importantly…automatic win conditions that the player/bot must meet to win the game during play and have the app “announce” that the game has ended and the winner?

For a noob like me, sometimes it is so easy to get into the game, that you forget to check if win conditions are being met during play.  😊

And just a question, is there a command to tell the app that the game has ended so it closes it out?  Or is it supposed to always be a save that can be resumed?

Thanks for all your help!

Ben

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sellmerfud** [comment] 2019-03-06 17:54
The program announce the winner if any of the victory conditions have been met during play.

Since the app does not handle cards, it is up to the player to determine victory after the last card has been played.  You can use the 'show summary' command to see the number of resources that are under Good/Islamist Rule.

**Comment by akyazi16** [comment] 2019-03-20 22:33
Hey Curt!

I think I might have identified another bug.  I have a situation where the Jihadist bot just played “Homegrown” which places a cell in the United Kingdom, however, funding for the Jihadists is “Tight” and there are no cells available on the funding track.  This card does not state “Ignoring Funding” in the text.  I believe the bot is supposed to Radicalize in this situation if I am interpreting the rules correctly.  The bot instructed me to place a cell in the United Kingdom anyway though.

I have attached my saved game for your reference.  Let me know if I’m wrong!

Ben

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
